### ISSUE TITLE
Deployment problem solution 

### ISSUE THREAD

**Issue by kumar045** [webprodigies/plura-production#10]
I have successfully deployed
https://agencymanagement.vercel.app/
If anyone facing any problem
Contact me for the help 
kumarshivam066@gmail.com

**Comment by yash-prajapati19** [comment]
error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (/mnt/d/pu-hackathon/node_modules/next/dist/compiled/edge-runtime/index.js:1:711758)
      at addPrimitives (/mnt/d/pu-hackathon/node_modules/next/dist/compiled/edge-runtime/index.js:1:710442)
      at extend (/mnt/d/pu-hackathon/node_modules/next/dist/compiled/edge-runtime/index.js:1:705225)  
      at new VM (/mnt/d/pu-hackathon/node_modules/next/dist/compiled/edge-runtime/index.js:1:712552)  
      at new EdgeVM (/mnt/d/pu-hackathon/node_modules/next/dist/compiled/edge-runtime/index.js:1:705155)
      at /mnt/d/pu-hackathon/node_modules/next/dist/server/web/sandbox/context.js:208:38
Watchpack Error (watcher): Error: AccessDenied

help me out with this error @kumar045

**Comment by HimanshuJ16** [comment]
> I have successfully deployed https://agencymanagement.vercel.app/ If anyone facing any problem Contact me for the help [kumarshivam066@gmail.com](mailto:kumarshivam066@gmail.com)

pls help me in how to deploy database only @kumar045

**Comment by bizibianca** [comment]
Hello @kumar045 , 
did you have any issues with the pipeline drag and drop, for some reason here is not working the draggable function.
