### ISSUE TITLE
can not make a team . and subaccount

### ISSUE THREAD

**Issue by mostafamosa** [webprodigies/plura-production#8]
the problem when i try to access team page . 
and can not make subaccount :(

![Screenshot 2024-02-05 021528](https://github.com/webprodigies/plura-production/assets/9301626/24dd9e4b-6f34-4b27-921c-9b253784cebb)

**Comment by Saptak-Bose** [comment]
please provide your env variables for further clarification of the error

**Comment by prit-nadoda** [comment]
> please provide your env variables for further clarification of the error

I am havin' an issue Team invitation is not being sent.
it goes like:
_ClerkAPIResponseError: Bad Request
    at InvitationAPI.eval [as request] (webpack-internal:///(rsc)/./node_modules/@clerk/backend/dist/esm/index.js:1189:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendInvitation (webpack-internal:///(rsc)/./src/lib/queries.ts:527:28)
    at async C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:406
    at async t0 (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:5773)
    at async rh (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:23636)
    at async doRender (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:1391:30)        
    at async cacheEntry.responseCache.get.routeKind (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:1540:40)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:1460:28)
    at async DevServer.renderPageComponent (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:1881:32)
    at async DevServer.pipeImpl (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\next-server.js:266:17)
    at async DevServer.handleRequestImpl (C:\Users\PIXEL-2UA6462L36\Desktop\plura\plura-changed\node_modules\next\dist\server\base-server.js:805:17) {
  toString: [Function (anonymous)],
  status: 400,
  clerkTraceId: 'cdc96beb30021faba3a79c22ca408bd4',
  clerkError: true,
  errors: [
    {
      code: 'invitations_not_supported',
      message: 'Invitations are only supported on instances that accept email addresses.',
      longMessage: 'Invitations are only supported on instances that accept email addresses.',
      meta: [Object]
    }
  ]
}
 ⨯ node_modules\@clerk\backend\dist\esm\index.js (1333:18) @ InvitationAPI.eval [as request]
 ⨯ Error: Bad Request
    at async sendInvitation (./src/lib/queries.ts:527:28)
null
![inviteError](https://github.com/user-attachments/assets/10b897b2-bb7b-4f3a-85df-a53dc6dab877)
